sudo: required
language: julia

os:
    - osx
    - linux

julia:
    - 1.0
    - nightly

notifications:
    email: true

matrix:
  allow_failures:
      - julia: nightly

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gcc; fi

after_success:
  - julia -e 'cd(Pkg.dir("ElasticFDA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
